version: "3.7"

services:
  db_pg:
    image: postgres
    container_name: db_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  api:
    build: .
    container_name: api_teste
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local